### ISSUE TITLE
Listing on alphabetical pages is inconsistent

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/pocom#15]
@joewiz : I noticed an oddity today. On some of the alphabetical pages, the names are written out firstname lastname:

https://history.state.gov/departmenthistory/people/by-name/e

However, on other pages, they are lastname, firstname:

https://history.state.gov/departmenthistory/people/by-name/h

Not sure why this is the case, but I wanted to bring it to your attention.

**Comment by joewiz** [comment]
@awmarrs Thanks! Strange, I'm not seeing this phenomenon - in both links the names are written out firstname lastname:

> ![screen shot 2017-04-04 at 7 35 45 pm](https://cloud.githubusercontent.com/assets/59118/24683591/fbd332ac-196d-11e7-8388-467b2cc2666d.png)

> ![screen shot 2017-04-04 at 7 35 36 pm](https://cloud.githubusercontent.com/assets/59118/24683594/06c7b8c2-196e-11e7-92df-14747920d1b8.png)

I've shift-reloaded to ensure my browser doesn't have a stale cache of the pages, and I've gone to the 1861- and 1991- variants of these pages. I've also checked on two separate machines, so the best explanation I can think of is that your browser has a stale cache of these pages. Could you try shift reloading and, if you're still seeing this, post a screenshot? (Command-shift-4 will let you draw a rectangle around a region and will deposit the screenshot on your desktop.)

**Comment by awmarrs** [comment]
OK, they are now correct for me too. I was just surprised because we had fixed this so long ago. My apologies!

**Comment by joewiz** [comment]
No worries!
