### ISSUE TITLE
A new type of concurrent appointment

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/pocom#7]
Joe,

While going through the principal officers data from Sara Jackson, I've discovered another type of concurrent appointment:

https://history.state.gov/departmenthistory/people/mccloskey-robert-james

McCloskey started out as Ambassador at Large, and was later appointed as A/S for Congressional Relations, and continued to serve as Ambassador at Large. When we first designed the concurrent appointments, I think (at least in my mind) they were intended to be appointments made at the same time, not positions which accrue over time (that is to say, you are *appointed* as Ambassador to Senegal and Guinea-Bissau at the same time, by the same presidential action).

Having said that, can you think of any reason why I can't continue to use the same concurrent appointment structure for these types of appointments? (I'd like to mark them somehow.) If you think the existing structure can also accommodate these, I'll use it, but if you want something different, let me know and we can chat.

**Comment by joewiz** [comment]
Hey Aaron, 

No, I don't see a problem using concurrent appointments to capture these cases where the concurrent positions were more staggered than we originally envisioned. I like the idea!

**Comment by awmarrs** [comment]
OK, super. Thanks!
